on:
  push:
  schedule:
    - cron: "0 * * * *"

jobs:
  unsplash_stats_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Updating blog posts
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: BLOG
        feed_list: "https://www.liandrowesley.dev/rss.xml"
    - name: Updating blog posts in English
      uses: gautamkrishnar/blog-post-workflow@master
      with:
        comment_tag_name: ENGLISH
        feed_list: "https://www.liandrowesley.dev/en/rss.xml"
